name: Build and deploy JAR library Maven repository

on:
  push:
    branches:
      - feature/1-release-as-a-library
  workflow_dispatch:

jobs:
  build_Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Build with Maven
        run: mvn deploy
